modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="more_s"
version="1.0.0"
displayName="More S"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Molianov, MCreator"

[[dependencies.more_s]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



